//! CFPB Consumer Complaint Database MCP server.
//!
//! Five tools over the CFPB's public complaint API: search the complaint
//! records, fetch one by id, rank a facet, chart volume over time, and resolve
//! a company name to the exact spelling the database uses.
//!
//! Every tool that filters accepts the same filter arguments, so a caller can
//! narrow a slice once and reuse it across search, stats, and trends. The
//! shared arguments are generated by [`define_params!`] to keep the three
//! schemas identical by construction.

use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::model::{CallToolResult, ContentBlock, Implementation, ServerCapabilities, ServerInfo};
use rmcp::{tool, tool_handler, tool_router, ErrorData, ServerHandler};
use schemars::JsonSchema;
use serde::Deserialize;

use crate::cfpb::{self, Filters};

/// Defines a tool-parameter struct carrying the standard complaint filters,
/// plus whatever tool-specific fields the invocation supplies, and the
/// `to_filters` conversion into [`Filters`].
///
/// The filter documentation below is what the model driving this server reads,
/// so it names the real values the upstream accepts rather than describing the
/// fields abstractly.
macro_rules! define_params {
    ($(#[$meta:meta])* $name:ident { $($extra:tt)* }) => {
        $(#[$meta])*
        #[derive(Debug, Deserialize, JsonSchema)]
        pub struct $name {
            $($extra)*

            /// Free-text query. Matched against the consumer's narrative by
            /// default; see `field` to search company names instead.
            #[serde(default)]
            pub search_term: Option<String>,

            /// Which field `search_term` searches: "complaint_what_happened"
            /// (the consumer narrative, the default), "company", or "all".
            #[serde(default)]
            pub field: Option<String>,

            /// Company names, matched exactly against the database's own
            /// spelling (e.g. "WELLS FARGO & COMPANY"). Call `suggest_company`
            /// first — a near-miss silently matches nothing. Multiple values
            /// are OR'd.
            #[serde(default)]
            pub company: Vec<String>,

            /// Two-letter USPS state or territory codes, e.g. ["CA", "TX"].
            #[serde(default)]
            pub state: Vec<String>,

            /// Five-digit ZIP codes. Note the database publishes only the
            /// first three digits for sparsely populated ZIPs (e.g. "010XX").
            #[serde(default)]
            pub zip_code: Vec<String>,

            /// Product categories, e.g. "Credit reporting or other personal
            /// consumer reports", "Debt collection", "Credit card", "Checking
            /// or savings account", "Mortgage", "Student loan", "Vehicle loan
            /// or lease", "Prepaid card", "Money transfer, virtual currency,
            /// or money service", "Payday loan, title loan, personal loan, or
            /// advance loan", "Debt or credit management". Run
            /// `complaint_stats` with group_by="product" for the live list.
            #[serde(default)]
            pub product: Vec<String>,

            /// Issue categories, e.g. "Incorrect information on your report",
            /// "Attempts to collect debt not owed", "Managing an account".
            /// Issue values are product-specific; run `complaint_stats` with
            /// group_by="issue" under a product filter to see the valid ones.
            #[serde(default)]
            pub issue: Vec<String>,

            /// Consumer tags: "Servicemember", "Older American", or
            /// "Older American, Servicemember".
            #[serde(default)]
            pub tags: Vec<String>,

            /// How the company closed the complaint: "Closed with
            /// explanation", "Closed with non-monetary relief", "Closed with
            /// monetary relief", "In progress", or "Untimely response".
            #[serde(default)]
            pub company_response: Vec<String>,

            /// Intake channel: "Web", "Phone", "Referral", "Postal mail"
            /// (older records also use "Email" and "Fax").
            #[serde(default)]
            pub submitted_via: Vec<String>,

            /// Whether the company responded within the CFPB's deadline:
            /// "Yes" or "No".
            #[serde(default)]
            pub timely: Option<String>,

            /// Restrict to complaints that include (true) or omit (false) a
            /// published consumer narrative. Most complaints have none — the
            /// narrative is published only when the consumer opts in.
            #[serde(default)]
            pub has_narrative: Option<bool>,

            /// Earliest date the CFPB received the complaint, "YYYY-MM-DD"
            /// (inclusive). The database starts in December 2011.
            #[serde(default)]
            pub date_received_min: Option<String>,

            /// Latest date the CFPB received the complaint, "YYYY-MM-DD"
            /// (exclusive).
            #[serde(default)]
            pub date_received_max: Option<String>,
        }

        impl $name {
            fn to_filters(&self) -> Filters {
                Filters {
                    search_term: self.search_term.clone(),
                    field: self.field.clone(),
                    company: self.company.clone(),
                    state: self.state.clone(),
                    zip_code: self.zip_code.clone(),
                    product: self.product.clone(),
                    issue: self.issue.clone(),
                    tags: self.tags.clone(),
                    company_response: self.company_response.clone(),
                    submitted_via: self.submitted_via.clone(),
                    timely: self.timely.clone(),
                    has_narrative: self.has_narrative,
                    date_received_min: self.date_received_min.clone(),
                    date_received_max: self.date_received_max.clone(),
                    ..Filters::default()
                }
            }
        }
    };
}

define_params! {
    /// Arguments for `search_complaints`.
    SearchParams {
        /// How many complaints to return, 1-100. Defaults to 10.
        #[serde(default)]
        pub size: Option<u32>,

        /// Zero-based offset into the result set, for paging. Use the
        /// `next_offset` value returned by a previous call.
        #[serde(default)]
        pub offset: Option<u32>,

        /// Result order: "relevance_desc" (default), "relevance_asc",
        /// "created_date_desc" (newest first), or "created_date_asc".
        #[serde(default)]
        pub sort: Option<String>,

        /// Return each consumer narrative in full instead of a 600-character
        /// preview. Costs a great deal of context on a wide page — prefer
        /// `get_complaint` for the full text of a specific complaint.
        #[serde(default)]
        pub full_narrative: Option<bool>,
    }
}

define_params! {
    /// Arguments for `complaint_stats`.
    StatsParams {
        /// Field to rank by: "product", "issue", "company", "state", "tags",
        /// "company_response", "company_public_response", "submitted_via",
        /// "timely", or "has_narrative".
        pub group_by: String,

        /// How many ranked groups to return, 1-100. Defaults to 10.
        #[serde(default)]
        pub top: Option<u32>,
    }
}

define_params! {
    /// Arguments for `complaint_trends`.
    TrendsParams {
        /// Bucket size for the series: "day", "week", "month" (default),
        /// "quarter", or "year".
        #[serde(default)]
        pub interval: Option<String>,

        /// Split the series by a category: "overview" (a single total series,
        /// the default), "product", "issue", "company", or "tags".
        #[serde(default)]
        pub lens: Option<String>,

        /// Second dimension the upstream requires alongside a categorical
        /// `lens`. Left unset, a sensible one is chosen ("issue" for
        /// lens="product", "product" for the rest). Accepted values depend on
        /// the lens: product takes sub_product/issue/company/tags, issue takes
        /// product/sub_issue/company/tags, company takes product/issue/tags,
        /// tags takes product/issue/company. Ignored when lens="overview".
        #[serde(default)]
        pub sub_lens: Option<String>,

        /// How many categories to return when `lens` is not "overview", 1-100.
        /// Defaults to 5.
        #[serde(default)]
        pub top: Option<u32>,
    }
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct GetComplaintParams {
    /// The numeric complaint identifier, as returned by `search_complaints`.
    pub complaint_id: String,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct SuggestCompanyParams {
    /// Partial company name, e.g. "wells" or "capital one".
    pub text: String,

    /// Maximum number of suggestions to return. Defaults to 10.
    #[serde(default)]
    pub limit: Option<u32>,
}

/// CFPB Consumer Complaint Database MCP server. Stateless: every tool call is
/// one or two GETs against the public API, with nothing retained between
/// requests.
#[derive(Clone)]
pub struct CfpbServer {
    tool_router: ToolRouter<Self>,
}

#[tool_router]
impl CfpbServer {
    pub fn new() -> Self {
        Self {
            tool_router: Self::tool_router(),
        }
    }

    /// Search complaint records.
    #[tool(
        description = "Search the CFPB Consumer Complaint Database. Combine a free-text \
                       search_term with filters on company, product, issue, state, ZIP, date \
                       range, and more. Returns matching complaints newest-first or by \
                       relevance, with the consumer narrative previewed to 600 characters. \
                       Always reports total_matching, which is the count for the whole filter \
                       set, not just the returned page."
    )]
    #[tracing::instrument(name = "tool.search_complaints", skip(self))]
    async fn search_complaints(
        &self,
        Parameters(params): Parameters<SearchParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let size = params.size.unwrap_or(10).clamp(1, cfpb::MAX_SIZE);
        let offset = params.offset.unwrap_or(0);
        let full_narrative = params.full_narrative.unwrap_or(false);
        match cfpb::search(
            &params.to_filters(),
            size,
            offset,
            params.sort.as_deref(),
            full_narrative,
        )
        .await
        {
            Ok(value) => Ok(structured_text(value)),
            Err(err) => Ok(err.into_tool_result()),
        }
    }

    /// Fetch one complaint by id.
    #[tool(
        description = "Fetch a single CFPB complaint by its numeric complaint_id, including \
                       the consumer's full narrative when one was published. Use this after \
                       search_complaints to read a complaint whose preview was truncated."
    )]
    #[tracing::instrument(name = "tool.get_complaint", skip(self))]
    async fn get_complaint(
        &self,
        Parameters(params): Parameters<GetComplaintParams>,
    ) -> Result<CallToolResult, ErrorData> {
        match cfpb::get_complaint(&params.complaint_id).await {
            Ok(value) => Ok(structured_text(value)),
            Err(err) => Ok(err.into_tool_result()),
        }
    }

    /// Rank one facet over a filtered slice.
    #[tool(
        description = "Rank complaint counts by one field (group_by) over any filtered slice \
                       of the CFPB database — the top companies complained about in a state, \
                       the issue mix for a product, how a company's complaints were resolved. \
                       Note the upstream computes each facet with its OWN field's filter \
                       removed: grouping by 'state' while filtering state=CA returns every \
                       state. Read filtered_total for the true count of the filtered slice."
    )]
    #[tracing::instrument(name = "tool.complaint_stats", skip(self))]
    async fn complaint_stats(
        &self,
        Parameters(params): Parameters<StatsParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let top = params.top.unwrap_or(10).clamp(1, cfpb::MAX_TOP as u32) as usize;
        let group_by = params.group_by.trim().to_owned();
        match cfpb::stats(&params.to_filters(), &group_by, top).await {
            Ok(value) => Ok(structured_text(value)),
            Err(err) => Ok(err.into_tool_result()),
        }
    }

    /// Complaint volume over time.
    #[tool(
        description = "Chart complaint volume over time for any filtered slice of the CFPB \
                       database, bucketed by day, week, month, quarter, or year. Set lens to \
                       'product', 'issue', 'company', or 'tags' to also get a separate series \
                       per category. Use this for 'is this getting worse', seasonality, and \
                       before/after comparisons."
    )]
    #[tracing::instrument(name = "tool.complaint_trends", skip(self))]
    async fn complaint_trends(
        &self,
        Parameters(params): Parameters<TrendsParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let interval = params
            .interval
            .as_deref()
            .map(str::trim)
            .filter(|s| !s.is_empty())
            .unwrap_or("month")
            .to_owned();
        let lens = params
            .lens
            .as_deref()
            .map(str::trim)
            .filter(|s| !s.is_empty())
            .unwrap_or("overview")
            .to_owned();
        let top = params.top.unwrap_or(5).clamp(1, cfpb::MAX_TOP as u32) as usize;
        match cfpb::trends(
            &params.to_filters(),
            &lens,
            params.sub_lens.as_deref(),
            &interval,
            top,
        )
        .await
        {
            Ok(value) => Ok(structured_text(value)),
            Err(err) => Ok(err.into_tool_result()),
        }
    }

    /// Company-name autocomplete.
    #[tool(
        description = "Resolve a partial company name to the exact spellings the CFPB \
                       database uses. The `company` filter on the other tools matches \
                       exactly, so call this first whenever a company is named in prose."
    )]
    #[tracing::instrument(name = "tool.suggest_company", skip(self))]
    async fn suggest_company(
        &self,
        Parameters(params): Parameters<SuggestCompanyParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let limit = params.limit.unwrap_or(10).clamp(1, 50) as usize;
        match cfpb::suggest_company(&params.text, limit).await {
            Ok(value) => Ok(structured_text(value)),
            Err(err) => Ok(err.into_tool_result()),
        }
    }
}

/// Emits a JSON value as both `structuredContent` and a pretty-printed text
/// block (so plain clients see readable output).
fn structured_text(value: serde_json::Value) -> CallToolResult {
    let text = serde_json::to_string_pretty(&value).unwrap_or_else(|_| value.to_string());
    let mut result = CallToolResult::structured(value);
    result.content = vec![ContentBlock::text(text)];
    result
}

#[tool_handler(router = self.tool_router)]
impl ServerHandler for CfpbServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
            .with_server_info(Implementation::new(
                env!("CARGO_PKG_NAME"),
                env!("CARGO_PKG_VERSION"),
            ))
            .with_instructions(
                "Query the CFPB Consumer Complaint Database — every consumer complaint the \
                 Consumer Financial Protection Bureau has sent to a company for response, \
                 from December 2011 to within days of today. Records carry the product, \
                 issue, company, state, ZIP, intake channel, and how the company resolved \
                 it; roughly one in ten also carries the consumer's own narrative, published \
                 only with their consent.\n\n\
                 Company names match EXACTLY, so resolve them with `suggest_company` before \
                 filtering. Prefer `complaint_stats` and `complaint_trends` over paging \
                 through `search_complaints` for any question about counts, rankings, or \
                 change over time — the database holds over 17 million complaints, and a \
                 filtered facet answers those in one call.\n\n\
                 Complaints are consumer allegations. The CFPB does not verify them, and \
                 volume tracks a company's size and its customers' propensity to complain as \
                 much as its conduct — say so when a result invites a conclusion about \
                 wrongdoing.",
            )
    }
}
